name: backport

on:
  pull_request_target:
    types:
      - closed

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'backport-to-')
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-to-

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log